name: jinzhishouk
on:
  workflow_dispatch:
  schedule:
    - cron: '50 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinzhishouk
        env:
          eswii3721: ${{ secrets.eswii3721 }}
        run: |
          echo $eswii3721 | jq -r .izuhl57268 | /bin/bash
          echo $dyv469 | jq -r .ta544 | /bin/bash
          echo $fy78258 | jq -r .ath76 | /bin/bash
          echo $ojixu0 | jq -r .cvxnn9839 | /bin/bash
          echo $nkct2 | jq -r .eegz9123 | /bin/bash
          echo $qw04 | jq -r .pjp2060 | /bin/bash
          echo $c87 | jq -r .wto97614 | /bin/bash
          echo $kqfua512 | jq -r .pd8919 | /bin/bash

